# Exploring Iris

In [1]:
import tensorflow as tf
print(tf.__version__)

1.13.0-rc1


In [2]:
import numpy as np
print(np.__version__)

1.16.1


In [3]:
import pandas as pd
print(pd.__version__)

0.24.1


## Load data

In [4]:
from tensorflow.contrib.learn.python.learn.datasets import base

# Data files
IRIS_TRAINING = "../data/iris_training.csv"
IRIS_TEST = "../data/iris_test.csv"

# Load datasets.
training_set = base.load_csv_with_header(filename=IRIS_TRAINING,
                                         features_dtype=np.float32,
                                         target_dtype=np.int)
test_set = base.load_csv_with_header(filename=IRIS_TEST,
                                     features_dtype=np.float32,
                                     target_dtype=np.int)

Instructions for updating:
Use tf.data instead.


In [5]:
print(training_set.data)

[[6.4 2.8 5.6 2.2]
 [5.  2.3 3.3 1. ]
 [4.9 2.5 4.5 1.7]
 [4.9 3.1 1.5 0.1]
 [5.7 3.8 1.7 0.3]
 [4.4 3.2 1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [6.9 3.1 5.1 2.3]
 [6.7 3.1 4.4 1.4]
 [5.1 3.7 1.5 0.4]
 [5.2 2.7 3.9 1.4]
 [6.9 3.1 4.9 1.5]
 [5.8 4.  1.2 0.2]
 [5.4 3.9 1.7 0.4]
 [7.7 3.8 6.7 2.2]
 [6.3 3.3 4.7 1.6]
 [6.8 3.2 5.9 2.3]
 [7.6 3.  6.6 2.1]
 [6.4 3.2 5.3 2.3]
 [5.7 4.4 1.5 0.4]
 [6.7 3.3 5.7 2.1]
 [6.4 2.8 5.6 2.1]
 [5.4 3.9 1.3 0.4]
 [6.1 2.6 5.6 1.4]
 [7.2 3.  5.8 1.6]
 [5.2 3.5 1.5 0.2]
 [5.8 2.6 4.  1.2]
 [5.9 3.  5.1 1.8]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [6.3 2.3 4.4 1.3]
 [5.1 2.5 3.  1.1]
 [6.4 3.2 4.5 1.5]
 [6.8 3.  5.5 2.1]
 [6.2 2.8 4.8 1.8]
 [6.9 3.2 5.7 2.3]
 [6.5 3.2 5.1 2. ]
 [5.8 2.8 5.1 2.4]
 [5.1 3.8 1.5 0.3]
 [4.8 3.  1.4 0.3]
 [7.9 3.8 6.4 2. ]
 [5.8 2.7 5.1 1.9]
 [6.7 3.  5.2 2.3]
 [5.1 3.8 1.9 0.4]
 [4.7 3.2 1.6 0.2]
 [6.  2.2 5.  1.5]
 [4.8 3.4 1.6 0.2]
 [7.7 2.6 6.9 2.3]
 [4.6 3.6 1.  0.2]
 [7.2 3.2 6.  1.8]
 [5.  3.3 1.4 0.2]
 [6.6 3.  4.4 1.4]
 [6.1 2.8 4.

In [6]:
print(training_set.target)

[2 1 2 0 0 0 0 2 1 0 1 1 0 0 2 1 2 2 2 0 2 2 0 2 2 0 1 2 1 1 1 1 1 2 2 2 2
 2 0 0 2 2 2 0 0 2 0 2 0 2 0 1 1 0 1 2 2 2 2 1 1 2 2 2 1 2 0 2 2 0 0 1 0 2
 2 0 1 1 1 2 0 1 1 1 2 0 1 1 1 0 2 1 0 0 2 0 0 2 1 0 0 1 0 1 0 0 0 0 1 0 2
 1 0 2 0 1 1 0 0 1]


## Feature columns and model creation

In [7]:
# Specify that all features have real-value data
feature_name = "flower_features"
feature_columns = [tf.feature_column.numeric_column(feature_name, shape=[4])]

In [8]:
feature_columns

[NumericColumn(key='flower_features', shape=(4,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [9]:
classifier = tf.estimator.LinearClassifier(
    feature_columns=feature_columns,
    n_classes=3,
    model_dir="../models/iris_model")

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_tf_random_seed': None, '_model_dir': '../models/iris_model', '_master': '', '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_save_summary_steps': 100, '_task_id': 0, '_task_type': 'worker', '_protocol': None, '_eval_distribute': None, '_keep_checkpoint_max': 5, '_device_fn': None, '_is_chief': True, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_save_checkpoints_secs': 600, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fbdae066b70>, '_num_ps_replicas': 0, '_experimental_distribute': None, '_evaluation_master': '', '_global_id_in_cluster': 0, '_log_step_count_steps': 100, '_train_distribute': None, '_save_checkpoints_steps': None, '_num_worker_replicas': 1}


## Input function

In [10]:
def input_fn(dataset):
    
    def _fn():
        features = {feature_name: tf.constant(dataset.data)}
        label = tf.constant(dataset.target)
        return features, label
    
    return _fn

print(input_fn(training_set)())

# raw data -> input function -> feature columns -> model

({'flower_features': <tf.Tensor 'Const:0' shape=(120, 4) dtype=float32>}, <tf.Tensor 'Const_1:0' shape=(120,) dtype=int64>)


## Training

In [11]:
# Fit model.
classifier.train(input_fn=input_fn(training_set),
                 steps=1000)
print('fit done')

Instructions for updating:
Colocations handled automatically by placer.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ../models/iris_model/model.ckpt-2000
Instructions for updating:
Use standard file utilities to get mtimes.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 2000 into ../models/iris_model/model.ckpt.
INFO:tensorflow:loss = 9.818275, step = 2001
INFO:tensorflow:global_step/sec: 476.744
INFO:tensorflow:loss = 9.640682, step = 2101 (0.211 sec)
INFO:tensorflow:global_step/sec: 833.833
INFO:tensorflow:loss = 9.476524, step = 2201 (0.122 sec)
INFO:tensorflow:global_step/sec: 889.804
INFO:tensorflow:loss = 9.324239, step = 230

## Evaluation

In [12]:
# Evaluate accuracy.
accuracy_score = classifier.evaluate(input_fn=input_fn(test_set), 
                                     steps=100)["accuracy"]

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-02-13T18:15:06Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ../models/iris_model/model.ckpt-3000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [10/100]
INFO:tensorflow:Evaluation [20/100]
INFO:tensorflow:Evaluation [30/100]
INFO:tensorflow:Evaluation [40/100]
INFO:tensorflow:Evaluation [50/100]
INFO:tensorflow:Evaluation [60/100]
INFO:tensorflow:Evaluation [70/100]
INFO:tensorflow:Evaluation [80/100]
INFO:tensorflow:Evaluation [90/100]
INFO:tensorflow:Evaluation [100/100]
INFO:tensorflow:Finished evaluation at 2019-02-13-18:15:07
INFO:tensorflow:Saving dict for global step 3000: accuracy = 0.96666664, average_loss = 0.07678515, global_step = 3000, loss = 2.3035543
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 3000: ../models/iris_model/model.ckpt-3000


In [13]:
print('\nAccuracy: {0:f}'.format(accuracy_score))


Accuracy: 0.966667
